[build-system]
requires = [
    "hatchling>=1.5.0",
    "jupyterlab>=4.0.0,<5",
    "hatch-nodejs-version",
    "markdownify",
    "autodoc-traits",
    "sphinx",
    "ruff",
]
build-backend = "hatchling.build"

[project]
name = "ipecharts"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = ["ipywidgets>=8,<9"]
dynamic = ["version", "description", "authors", "urls", "keywords"]

[tool.hatch.version]
source = "nodejs"

[tool.hatch.metadata.hooks.nodejs]
fields = ["description", "authors", "urls"]

[tool.hatch.build.targets.sdist]
artifacts = ["ipecharts/labextension", "ipecharts/option"]
exclude = [".github", "binder"]

[tool.hatch.build.targets.wheel]
artifacts = ["ipecharts/option"]
exclude = [".github", "binder", "generate_code"]

[tool.hatch.build.targets.wheel.shared-data]
"ipecharts/labextension" = "share/jupyter/labextensions/ipecharts"
"ipecharts/nbextension" = "share/jupyter/nbextensions/ipecharts"
"install.json" = "share/jupyter/labextensions/ipecharts/install.json"
"ipecharts.json" = "etc/jupyter/nbconfig/notebook.d/ipecharts.json"

[tool.hatch.build.hooks.version]
path = "ipecharts/_version.py"

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder>=0.5"]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = [
    "ipecharts/labextension/static/style.js",
    "ipecharts/labextension/package.json",
    "ipecharts/nbextension/index.js",
]
skip-if-exists = [
    "ipecharts/labextension/static/style.js",
    "ipecharts/nbextension/index.js",
    "ipecharts/_option.py",
]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.hatch.build.hooks.jupyter-builder.editable-build-kwargs]
build_cmd = "install:extension"
npm = ["jlpm"]
source_dir = "src"
build_dir = "ipecharts/labextension"

[tool.jupyter-releaser.options]
version_cmd = "hatch version"

[tool.jupyter-releaser.hooks]
before-build-npm = [
    "python -m pip install 'jupyterlab>=4.0.0,<5' markdownify ruff autodoc-traits sphinx",
    "jlpm",
    "jlpm build:prod",
]
before-build-python = ["jlpm clean:all"]

[tool.check-wheel-contents]
ignore = ["W002"]

[tool.ruff]
respect-gitignore = false

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
